language: ruby
sudo: false
rvm:
  - 2.1.0
  - 2.2.0
  - 2.0.0
  - ruby-head
services:
  - rabbitmq
install:
  - gem uninstall bundler
  - gem install bundler --version '1.10.6'
  - eval bundle install --jobs=3 --retry=3 --deployment --verbose
